; PlatformIO Project Configuration File for LilyGo TTGO T5 V2.3.1 - Picture Frame
[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
board_build.partitions = no_ota.csv

upload_speed = 921600
monitor_speed = 115200

extra_scripts = pre:../load_env.py

build_flags = 
    -DCORE_DEBUG_LEVEL=0
    -DEPD_CS=5
    -DEPD_DC=17
    -DEPD_RST=16
    -DEPD_BUSY=4
    -DEPD_SCK=18
    -DEPD_MOSI=23
    -DADC_PIN=35
    -DBUTTON_PIN=39

lib_deps =
    zinggjm/GxEPD2 @ ^1.5.9
    olikraus/U8g2_for_Adafruit_GFX @ ^1.8.0
    bblanchon/ArduinoJson @ ^7.2.1
    ricmoo/QRCode @ ^0.0.1
